First ECAL implementation
AliceO2Group/DelphesO2 pull request #120
Opened 2021-09-11 22:02 UTC by kharlov

2021-09-16 10:29 UTC, njacazio commented
Hi @kharlov please trigger me when you need to have this PR reviewed

2021-09-23 11:23 UTC, kharlov commented
Hi @njacazio , I fixed several bugs in ECAL response, please check and merge the new PR.

2021-09-23 13:48 UTC, njacazio requested changes
Hi @kharlov  good work! Could you also run `clang-format -i` on the files that you changed so as to uniformize the style?
If it does not work it should be possible to do it from inside the alienv environment

2021-09-23 13:48 UTC, njacazio commented on examples/aod/createO2tables.C
> +const double tof_sigmat0 = 0.20;
This should not need to be changed

2021-09-23 13:48 UTC, njacazio commented on examples/aod/createO2tables.C
> +constexpr bool enable_nuclei = true;
This should not need to be changed

2021-09-23 13:48 UTC, njacazio commented on examples/aod/createO2tables.C
> +      if (ecal_detector.makeSignal(*particle, pECAL, posZ, posPhi)) { // to be updated 13.09.2021
The initalization of the TLorentzVector could be done once and used outside of the loop for tracks

2021-09-23 13:49 UTC, njacazio commented
Also, there are some conflicts that have to solved before this can be merged

2021-09-23 17:05 UTC, kharlov commented
Hi @njacazio , I solved conflicts, ran clang and opened a new PR. Did I do it correctly?

2021-09-24 08:12 UTC, njacazio commented
Hi Yuri, yes, I will have a look asap

2021-09-27 10:06 UTC, njacazio commented
Hi @kharlov your changes will be merged from here https://github.com/AliceO2Group/DelphesO2/pull/126

2021-09-27 10:46 UTC, kharlov commented
Hi @njacazio , I fixed one more bug in ECAL response: photon hit coordinate was not calculated correctly.

2021-09-27 11:12 UTC, njacazio commented
Hi, @kharlov, perfect, I will include it in the software as soon as you push it in this PR

2021-09-27 11:13 UTC, njacazio commented
Ah, I just saw that you already did, I will import it now

2021-09-27 12:33 UTC, njacazio commented
Closing as already merged in other PR

2021-09-27 12:33 UTC, closed without merging