First implementation of Photon Conversion
AliceO2Group/DelphesO2 pull request #125
Opened 2021-09-22 17:31 UTC by amaringarcia

2021-09-24 08:13 UTC, njacazio commented
Hi @amaringarcia tell us when ready for review

2021-09-24 08:20 UTC, amaringarcia commented
Every thin compiles, DelphesO2 runs, the AODs are filled. The only point missing is to check that the resolution and the efficiency is what I have plug in. I am writing a program for that. Any macro/program that reads MC particle and compared to reco one will help. 
So, in my opinion the review can already happen.

2021-09-27 08:15 UTC, njacazio requested changes
Hi, good work! If you could take care of the suggestions we can merge this

2021-09-27 08:15 UTC, njacazio commented on examples/aod/createO2tables.C
> +
Maybe it is worth to create the TLorentzVector only once outside of the loop and use it many times in the loop

2021-09-27 08:15 UTC, njacazio commented on examples/aod/createO2tables.C
> +	pres.fIndexCollisions = ientry + eventOffset;
Could you use clang-format on the file? i.e. `clang-format -i createO2tables.C`

2021-09-27 08:15 UTC, njacazio commented on examples/aod/createO2tables.h
> +				  "O2photonconv",
Could you also run the formatter on the `.h` file?

2021-09-27 08:15 UTC, njacazio commented on rpythia8/rpythia8-box.cc
> +    if (  abs(pdg) < 1000000000 && pdg != 22) {
Also this should be formatted with clang-format

2021-09-27 08:15 UTC, njacazio commented on src/PhotonConversion.cc
> +
It would be useful for the future to format also this piece of code

2021-09-27 08:15 UTC, njacazio commented on src/PhotonConversion.cc
> +      // auto y = track.YOuter * 0.1; // [cm]
Could this be cleaned?

2021-09-27 08:15 UTC, njacazio commented on src/PhotonConversion.cc
> +      // Float_t vtY = particle.Y; // particle vertex Y
Could this be cleaned as well?

2021-09-27 08:15 UTC, njacazio commented on src/PhotonConversion.cc
> +    //   return dX;
This might be removed?

2021-09-27 08:15 UTC, njacazio commented on src/PhotonConversion.hh
> +    public:
Maybe we could format also this

2021-09-28 11:13 UTC, amaringarcia commented
I have followed your suggestions....
Please, let me know if it is ok now, or I should do other changes

2021-10-01 12:27 UTC, njacazio requested changes
Dear @amaringarcia great work! Please consider the last comments and then we can merge it, as a general comment please avoid changing the code that is not strictly needed as it makes review harder. Also, don't forget to run `clang-format` as it allows to avoid some not needed changes (except for the rpythia code where the configuration becomes hard to read)

2021-10-01 12:27 UTC, njacazio commented on rpythia8/rpythia8-box.cc
> +  if (!pythia.particleData.isParticle(pdg) ) {
This change probably can be avoided

2021-10-01 12:27 UTC, njacazio commented on rpythia8/rpythia8-box.cc
> +
idem

2021-10-01 12:27 UTC, njacazio commented on rpythia8/rpythia8-box.cc
> +
idem

2021-10-01 12:27 UTC, njacazio commented on rpythia8/rpythia8.cc
> +    desc.add_options()("help", "Print help messages")("nevents,n", po::value<int>(&nevents)->default_value(10), "Number of events")("config,c", po::value<std::string>(&config), "Configuration file")(
This is not easy to read, it would be best to not do it

2021-10-01 12:27 UTC, njacazio commented on examples/aod/createO2tables.C
> +  //  photon_conversion.setup();
This could be cleaned

2021-10-01 12:27 UTC, njacazio commented on examples/aod/createO2tables.h
> +
This could  stay the same, probably it can be fixed by running clang-format

2021-10-01 15:14 UTC, amaringarcia commented on rpythia8/rpythia8.cc
> +    desc.add_options()("help", "Print help messages")("nevents,n", po::value<int>(&nevents)->default_value(10), "Number of events")("config,c", po::value<std::string>(&config), "Configuration file")(
I am not aware of having changed this file

2021-10-04 09:49 UTC, njacazio commented
Ok, great, let me try this to verify that it compiles and we are set

2021-10-04 11:40 UTC, merged

2021-10-04 11:43 UTC, amaringarcia commented
Thanks a lot. Sorry for all the extra work.!